name: lastre3ayty
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.0
  firebase_messaging: ^7.0.3
  flutter_staggered_animations: ^1.0.0
  flutter_rating_bar: ^4.0.0
  unicorndial: ^1.1.5
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  dio:
  shared_preferences: ^2.0.6
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.0.0
  google_maps_flutter: ^2.0.1
  google_map_location_picker: ^4.1.7
  image_picker: ^0.8.0+3
  get_storage: ^2.0.2
  pin_code_text_field: ^1.8.0

  multiselect_formfield: any


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: 'assets/images/newlogo.png'
  image_path_android: 'assets/images/newlogo.png'
  image_path_ios: 'assets/images/newlogo.png'
  android: true
  ios: true


# The following section is specific to Flutter.
flutter:


  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/flare/

  fonts:
    - family: Cairo-Bold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
  #        weight: 700
    - family: Cairo-Regular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
